### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by ykdojo** [Moinch/CapstoneCodebase#2]
Hello @Moinch! Thank you for signing up to [our bootcamp program](https://github.com/sponsors/ykdojo).

I'm making an issue here because I couldn't find any other contact info on your profile.

Do you mind sharing your Discord profile so I can add you on our server?

**Comment by MoinChaudhry** [comment]
Chaudhrymoin7@gmail.com

username: MC2001#6548

**Comment by ykdojo** [comment]
Thank you. Here's an invite to the server: https://discord.com/invite/nNtVfKddDD

Once you are there, let me know so I can add you to the correct role

**Comment by MoinChaudhry** [comment]
Thanks

**Comment by MoinChaudhry** [comment]
Just joined!

**Comment by ykdojo** [comment]
Thank you. I don't see MC2001#6548 though

**Comment by MoinChaudhry** [comment]
Seems like I had missed a step. I am in now.
